### ISSUE TITLE
模型如何C++推理

### ISSUE THREAD

**Issue by Dandelion111** [huaifeng1993/DFANet#40]
请问这个模型可以用C++推理吗？哪个工具支持这个模型的推理

**Comment by huaifeng1993** [comment]
pc端可以使用libtorch。嵌入端可以转onnx，然后使用使用适配的嵌入段onnx框架推理。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huaifeng1993/DFANet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 下午3:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[huaifeng1993/DFANet] 模型如何C++推理 (#40)





 
请问这个模型可以用C++推理吗？哪个工具支持这个模型的推理
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
